name: simple_app
description: SimPLE - Asistente de compras

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_simple.jpg

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/logo_simple.jpg
  adaptive_icon_background: "#0057C2"
  adaptive_icon_foreground: assets/logo_simple.jpg

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo_simple.jpg
  android: true
  ios: false
  android_gravity: center
  android_12:
    image: assets/logo_simple.jpg
    color: "#FFFFFF"
